laba12/laba12/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace laba12.Models
{
    public class Department
    {
        public int Id { get; set; }

        public string Address { get; set; }

        public DateTime CreatedDate { get; set; }
    }
}

laba12/laba12/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace laba12.Models
{
    public class Employee
    {
        public int Id { get; set; }

        public int? DepartmentId { get; set; }

        public int? PositionId { get; set; }

        public DateTime? DateOfHiring { get; set; }

        public DateTime? DateOfFiring { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string MiddleName { get; set; }

        public string Gender { get; set; }

        public string PassportNumber { get; set; }

        public string Address { get; set; }

        public string Phone { get; set; }
    }
}

laba12/laba12/Models/ErrorViewModel.cs
using System;

namespace laba12.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

laba12/laba12/Models/Position.cs
namespace laba12.Models
{
    public class Position
    {
        public int Id { get; set; }

        public string PositionName { get; set; }
    }
}

laba12/laba12/Controllers/DepartmentController.cs
using laba12.Models;
using laba12.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace laba12.Controllers
{
    public class DepartmentController : Controller
    {
        private DepartmentService departmentService = new DepartmentService();

        public ActionResult List()
        {
            var model = departmentService.GetDepartmentsList();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Department model)
        {
            departmentService.InsertDepartment(model);

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var model = departmentService.GetDepartmentById(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Department model)
        {
            departmentService.UpdateDepartment(model);

            return RedirectToAction("List");
        }

        public ActionResult Delete(int id)
        {
            departmentService.DeleteDepartment(id);

            return RedirectToAction("List");
        }
    }
}

laba12/laba12/Controllers/EmployeeController.cs
using laba12.Models;
using laba12.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace laba12.Controllers
{
    public class EmployeeController : Controller
    {
        private EmployeeService employeeService = new EmployeeService();

        public ActionResult List()
        {
            var model = employeeService.GetEmployeesList();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Employee model)
        {
            employeeService.InsertEmployee(model);

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var model = employeeService.GetEmployeeById(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Employee model)
        {
            employeeService.UpdateEmployee(model);

            return RedirectToAction("List");
        }

        public ActionResult Delete(int id)
        {
            employeeService.DeleteEmployee(id);

            return RedirectToAction("List");
        }
    }
}

laba12/laba12/Controllers/HomeController.cs
using laba12.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace laba12.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

laba12/laba12/Controllers/PositionController.cs
using laba12.Models;
using laba12.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace laba12.Controllers
{
    public class PositionController : Controller
    {
        private PositionService positionService = new PositionService();

        public ActionResult List()
        {
            var model = positionService.GetPositionsList();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Position model)
        {
            positionService.InsertPosition(model);

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var model = positionService.GetPositionById(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Position model)
        {
            positionService.UpdatePosition(model);

            return RedirectToAction("List");
        }

        public ActionResult Delete(int id)
        {
            positionService.DeletePosition(id);

            return RedirectToAction("List");
        }
    }
}

laba12/laba12/Views/Department/Create.cshtml
@model laba12.Models.Department

@{
    ViewData["Title"] = "Create department";
}

<h1>Create department</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

laba12/laba12/Views/Department/Edit.cshtml
@model laba12.Models.Department

@{
    ViewData["Title"] = "Edit department";
}

<h1>Edit department</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

laba12/laba12/Views/Department/List.cshtml
@model IEnumerable<laba12.Models.Department>

@{
    ViewData["Title"] = "Department list";
}

<h1>Departments list</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

laba12/laba12/Views/Employee/Create.cshtml
@model laba12.Models.Employee

@{
    ViewData["Title"] = "Create employee";
}

<h1>Create employee</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <input asp-for="DepartmentId" class="form-control" />
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PositionId" class="control-label"></label>
                <input asp-for="PositionId" class="form-control" />
                <span asp-validation-for="PositionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfHiring" class="control-label"></label>
                <input asp-for="DateOfHiring" class="form-control" />
                <span asp-validation-for="DateOfHiring" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfFiring" class="control-label"></label>
                <input asp-for="DateOfFiring" class="form-control" />
                <span asp-validation-for="DateOfFiring" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportNumber" class="control-label"></label>
                <input asp-for="PassportNumber" class="form-control" />
                <span asp-validation-for="PassportNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

laba12/laba12/Views/Employee/Edit.cshtml
@model laba12.Models.Employee

@{
    ViewData["Title"] = "Edit employee";
}

<h1>Edit employee</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <input asp-for="DepartmentId" class="form-control" />
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PositionId" class="control-label"></label>
                <input asp-for="PositionId" class="form-control" />
                <span asp-validation-for="PositionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfHiring" class="control-label"></label>
                <input asp-for="DateOfHiring" class="form-control" />
                <span asp-validation-for="DateOfHiring" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfFiring" class="control-label"></label>
                <input asp-for="DateOfFiring" class="form-control" />
                <span asp-validation-for="DateOfFiring" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportNumber" class="control-label"></label>
                <input asp-for="PassportNumber" class="form-control" />
                <span asp-validation-for="PassportNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

laba12/laba12/Views/Employee/List.cshtml
@model IEnumerable<laba12.Models.Employee>

@{
    ViewData["Title"] = "Employee List";
}

<h1>Employees list</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PositionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfHiring)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfFiring)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassportNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PositionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfHiring)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfFiring)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PassportNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

laba12/laba12/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>Artsiom Kharkevich lab 12.</p>

laba12/laba12/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-4">Lab12</h3>
    <p>@Html.ActionLink("Positions", "List", "Position")</p>
    <p>@Html.ActionLink("Departments", "List", "Department")</p>
    <p>@Html.ActionLink("Employees", "List", "Employee")</p>
</div>

laba12/laba12/Views/Position/Create.cshtml
@model laba12.Models.Position

@{
    ViewData["Title"] = "Create position";
}

<h1>Create position</h1>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PositionName" class="control-label"></label>
                <input asp-for="PositionName" class="form-control" />
                <span asp-validation-for="PositionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

laba12/laba12/Views/Position/Edit.cshtml
@model laba12.Models.Position

@{
    ViewData["Title"] = "Edit position";
}

<h1>Edit position</h1>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PositionName" class="control-label"></label>
                <input asp-for="PositionName" class="form-control" />
                <span asp-validation-for="PositionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

laba12/laba12/Views/Position/List.cshtml
@model IEnumerable<laba12.Models.Position>

@{
    ViewData["Title"] = "List position";
}

<h1>Positions list</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PositionName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PositionName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

laba12/laba12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - laba12</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">laba12</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - laba12 - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>